name: GitHub Classroom Workflow
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v3

      # TODO build and run unit tests

      - name: Build images
        timeout-minutes: 10
        working-directory: ./src
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        working-directory: ./src
        run: |
          docker compose up -d
          # Path updated to look inside backend/scripts/
          chmod +x ./backend/scripts/wait-script.sh
          ./backend/scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v2/postman/collection.json
          environment: v2/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Stop containers
        if: always()
        continue-on-error: true
        working-directory: ./src
        run: docker compose down -v
