name: GitHub Classroom Workflow
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v3

      # TODO build and run unit tests

      - name: Build images
        timeout-minutes: 10
        working-directory: ./src
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        working-directory: ./src
        run: |
          docker compose up -d
          
          echo "Waiting for services to become healthy..."
          PORTS=(8080 8070 8060 8050)
          
          for PORT in "${PORTS[@]}"; do
            echo "Checking port $PORT..."
            TIMEOUT=30
            while [ $TIMEOUT -gt 0 ]; do
              if nc -z localhost $PORT; then
                echo "✅ Port $PORT is active!"
                break
              fi
              sleep 1
              TIMEOUT=$((TIMEOUT - 1))
            done
            
            if [ $TIMEOUT -eq 0 ]; then
              echo "❌ Port $PORT timed out! Printing diagnostics..."
              docker compose logs
              exit 1
            fi
          done

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v2/postman/collection.json
          environment: v2/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Stop containers
        if: always()
        continue-on-error: true
        working-directory: ./src
        run: docker compose down -v
